### ISSUE TITLE
Problem with one-particle star file

### ISSUE THREAD

**Issue by hamid13r** [alisterburt/dynamo2m#6]
Hi Alister,

I have a problem running the warp2dynamo script and it seems to only happen when the star file only have one particle.

```
Traceback (most recent call last):
  File "/home/janlevinson/micromamba/envs/dynamo/bin/warp2dynamo", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/janlevinson/micromamba/envs/dynamo/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janlevinson/micromamba/envs/dynamo/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/janlevinson/micromamba/envs/dynamo/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janlevinson/micromamba/envs/dynamo/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/janlevinson/micromamba/envs/dynamo/lib/python3.12/site-packages/dynamo2m/warp2dynamo.py", line 108, in cli
    warp2dynamo(warp_star_file, dynamo_table_file, extracted_box_size)
  File "/home/janlevinson/micromamba/envs/dynamo/lib/python3.12/site-packages/dynamo2m/warp2dynamo.py", line 38, in warp2dynamo
    dynamo_data['tdrot'] = eulers_dynamo[:, 0]
                           ~~~~~~~~~~~~~^^^^^^
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
The error goes away after adding a dummy line. 

I know this is a very rare case. But we do often work on very rare targets. 

H

**Comment by alisterburt** [comment]
Hey Hamid, thanks for reporting... the fix should be as simple as `eulers_dynamo[:, 0]` -> `eulers_dynamo.reshape((-1, 2))[:, 0]`

This package is ~4 years old and I don't have the infrastructure in place to push a fix to PyPI easily so won't update the package
